### ISSUE TITLE
Change name of repo?

### ISSUE THREAD

**Issue by MylesBorins** [tc39/proposal-built-in-modules#53]
At the end of the last meeting I believe the proposal had an official name change to "builtin-modules" should we adjust the repo accordingly?

**Comment by msaboff** [comment]
I'm fine with changing the repro name.  Is it possible to create a forwarding link?

**Comment by xtuc** [comment]
GitHub will automatically redirect the old repo to the new one.

**Comment by andrewrabon** [comment]
Maybe pedantic but I'm genuinely curious:

Why `Builtin Modules` and not `Built-In Modules` or similar?

**Comment by kaizhu256** [comment]
to avoid extra ux-transformation headache of renaming `Built-In` -> `Built_In` or `BuiltIn` for js-variables that may be associated with it.
